ports:
  - port: 5173
    visibility: public
    onOpen: open-browser

tasks:
  - name: Run dev server
    init: |
      npm install
      gp sync-done install
    command: npm run dev
  - name: Show outdated packages
    init: gp sync-await install
    command: npm outdated
    openMode: split-right

vscode:
  extensions:
    - bradlc.vscode-tailwindcss
    - csstools.postcss
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - mattpocock.ts-error-translator
    - rangav.vscode-thunder-client
    - robole.marky-stats
    - svelte.svelte-vscode

github:
  prebuilds:
    main: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: prevent-merge-on-error
    addComment: false
    addBadge: false
