name: CI

on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize]

# With pre-rendering enabled, build loads modules, which triggers imports.
# These variables are just dummies that need to exist while build and check run.
env:
  EO_API_KEY: ${{ secrets.EO_API_KEY }}
  EO_LIST_ID: ${{ secrets.EO_LIST_ID }}
  IMGIX_DOMAIN: ${{ secrets.IMGIX_DOMAIN }}
  IMGIX_TOKEN: ${{ secrets.IMGIX_TOKEN }}
  ORIGIN: ${{ secrets.ORIGIN }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_REMOTE_ONLY: true

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      # tsconfig.json extends ./.sveltekit/tsconfig.json, which is created during build.
      - name: Build
        run: npm run build

      - name: Check
        run: npm run check
