name: CI

on: [pull_request]

# With pre-rendering enabled, build loads modules, which triggers imports.
# These variables are just dummies that need to exist while build and check run.
env:
  EO_API_KEY: ${{ secrets.EO_API_KEY }}
  EO_LIST_ID: ${{ secrets.EO_LIST_ID }}
  IMGIX_DOMAIN: ${{ secrets.IMGIX_DOMAIN }}
  IMGIX_TOKEN: ${{ secrets.IMGIX_TOKEN }}

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - run: npm ci
      - run: npm run lint
      # tsconfig.json extends ./.sveltekit/tsconfig.json, which is created during build.
      - run: npm run build
      - run: npm run check
