name: CI
on: [pull_request]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - run: npm ci
      - run: npm run lint
      # tsconfig.json extends ./.sveltekit/tsconfig.json, which is created during build.
      - run: npm run build
      - run: npm run check
